[package]
name = "mockMoretoe_createPlan"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
iced = { version = "0.14.0", features = ["image"] }
serde = { version = "1.0.228", features = "derive"}
uuid = "1.21.0"
